// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzyPTxkXWbVCQsvUFRpSFb3SiewDZoM4k',
    appId: '1:678715415011:web:22a5baf2354a470750e8d6',
    messagingSenderId: '678715415011',
    projectId: 'ecotrak-65cb0',
    authDomain: 'ecotrak-65cb0.firebaseapp.com',
    storageBucket: 'ecotrak-65cb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvhdF8AaO9zExqm2dxYeQKT5KEeHVEJ0',
    appId: '1:678715415011:android:1ca451d82ea3405050e8d6',
    messagingSenderId: '678715415011',
    projectId: 'ecotrak-65cb0',
    storageBucket: 'ecotrak-65cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cd3K8DkUjlXS8pKgGL7y7FmzFCXpE2E',
    appId: '1:678715415011:ios:7f5168cb7c6e3aa450e8d6',
    messagingSenderId: '678715415011',
    projectId: 'ecotrak-65cb0',
    storageBucket: 'ecotrak-65cb0.appspot.com',
    iosClientId: '678715415011-5ge7hv2f8d4c9e8ph7tv7sabk8q0n7bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecotrakDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_cd3K8DkUjlXS8pKgGL7y7FmzFCXpE2E',
    appId: '1:678715415011:ios:0abf674315c62d0b50e8d6',
    messagingSenderId: '678715415011',
    projectId: 'ecotrak-65cb0',
    storageBucket: 'ecotrak-65cb0.appspot.com',
    iosClientId: '678715415011-uj2avo9sn15ld0bqeonunc1lt2rn18l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecotrakDriver.RunnerTests',
  );
}
